# Generated by Django 4.2.23 on 2025-07-10 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riddles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="option",
            old_name="correct",
            new_name="is_correct",
        ),
        migrations.RemoveField(
            model_name="riddle",
            name="pub_date",
        ),
        migrations.RemoveField(
            model_name="riddle",
            name="riddle_text",
        ),
        migrations.AddField(
            model_name="riddle",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2025, 7, 10, 2, 56, 16, 742193),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="riddle",
            name="text",
            field=models.CharField(default="Default riddle", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="option",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="text",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="riddle",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
